#!/usr/bin/env python3
"""FreeInkMaps map tile generator.

Turns a folder of 1-bit XYZ map tile PNGs into compiled-in freeink::maps::MapTile
C++ data for mapView() — the same "generate only what you use" approach as the
Icon and font tooling: no on-device PNG decode, no heap, no file IO.

Expects the standard `{z}/{x}/{y}.png` XYZ tile-folder layout that most slippy-map
tools export. A convenient source is HarukiToreda's E-ink Map Tiles desktop app
(https://github.com/HarukiToreda/E-ink-Map-Tiles): export with mode `mono` (or
`inkhud`) and point --tiles-dir at the resulting `tiles/<style>/` folder. Carry
that source's required OpenStreetMap/OpenFreeMap attribution with anything built
from its tiles (see its README's Attribution section) — this tool does not embed
that for you.

Usage:
    gen_maptiles.py --tiles-dir tiles/osm-eink --zoom 16 --out generated_maptiles.h

Requires: Pillow.
"""
import argparse
import os
import re
import sys

from PIL import Image


def pack(img, size):
    """Pack an e-paper tile to 1-bpp, MSB-first, row-major, bit=1 is ink
    (BitmapFormat::BW1's convention — the opposite polarity from freeink::Icon's
    Mask1). Pixels darker than --threshold count as ink."""
    pix = img.load()
    data = bytearray()
    for y in range(size):
        byte = 0
        bits = 0
        for x in range(size):
            ink = 1 if pix[x, y] else 0
            byte = (byte << 1) | ink
            bits += 1
            if bits == 8:
                data.append(byte)
                byte = 0
                bits = 0
        if bits:
            data.append(byte << (8 - bits))
    return bytes(data)


def ident(zoom, tx, ty):
    return f"kTileZ{zoom}X{tx}Y{ty}"


def find_tiles(tiles_dir, zoom_filter):
    tile_re = re.compile(r"^(\d+)\.png$")
    found = []
    for zoom_name in sorted(os.listdir(tiles_dir)):
        zoom_dir = os.path.join(tiles_dir, zoom_name)
        if not os.path.isdir(zoom_dir) or not zoom_name.isdigit():
            continue
        zoom = int(zoom_name)
        if zoom_filter is not None and zoom != zoom_filter:
            continue
        for x_name in sorted(os.listdir(zoom_dir), key=lambda s: int(s) if s.isdigit() else s):
            x_dir = os.path.join(zoom_dir, x_name)
            if not os.path.isdir(x_dir) or not x_name.isdigit():
                continue
            tx = int(x_name)
            for y_name in sorted(os.listdir(x_dir)):
                m = tile_re.match(y_name)
                if not m:
                    continue
                ty = int(m.group(1))
                found.append((zoom, tx, ty, os.path.join(x_dir, y_name)))
    return found


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tiles-dir", required=True, help="folder containing {z}/{x}/{y}.png tiles")
    ap.add_argument("--zoom", type=int, default=None, help="only include this zoom level (default: all found)")
    ap.add_argument("--tile-size", type=int, default=256, help="tile width/height in pixels (default 256)")
    ap.add_argument("--threshold", type=int, default=128, help="grayscale cutoff for ink, 0-255 (default 128)")
    ap.add_argument("--array-name", default="kMapTiles", help="generated MapTile array identifier")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    tiles = find_tiles(args.tiles_dir, args.zoom)
    if not tiles:
        print(f"no tiles found under {args.tiles_dir}", file=sys.stderr)
        return 1

    out = []
    out.append("#pragma once")
    out.append("")
    out.append("// Generated by tools/gen_maptiles.py — do not edit by hand.")
    out.append("")
    out.append("#include <FreeInkMapsCore.h>")
    out.append("")
    out.append("namespace freeink {")
    out.append("namespace maps {")
    out.append("")

    entries = []
    for zoom, tx, ty, path in tiles:
        img = Image.open(path).convert("L")
        if img.size != (args.tile_size, args.tile_size):
            img = img.resize((args.tile_size, args.tile_size))
        img = img.point(lambda p, t=args.threshold: 1 if p < t else 0)
        body = ",".join(str(b) for b in pack(img, args.tile_size))
        arr = ident(zoom, tx, ty)
        out.append(f"static const uint8_t {arr}[] = {{{body}}};")
        entries.append((zoom, tx, ty, arr))

    out.append("")
    out.append(f"static const MapTile {args.array_name}[] = {{")
    for zoom, tx, ty, arr in entries:
        out.append(
            f"    MapTile{{{zoom}, {tx}, {ty}, "
            f"BitmapRef{{{arr}, {args.tile_size}, {args.tile_size}, BitmapFormat::BW1, false}}}},"
        )
    out.append("};")
    out.append(f"static const uint16_t {args.array_name}Count = {len(entries)};")
    out.append("")
    out.append("}  // namespace maps")
    out.append("}  // namespace freeink")
    out.append("")

    with open(args.out, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {len(entries)} tile(s) to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
